### ISSUE TITLE
issues on dataset

### ISSUE THREAD

**Issue by ruchika61** [ssedai026/semantic-image-segmentation#1]
Hi
How you have prepared dataset. I  didn't find dataflow. kindly sugest.

**Comment by ssedai026** [comment]
mnist segmentation data can be generated using mnist_generate_data.py. You can then run train_mnist_segmentation.py to start training.

**Comment by ruchika61** [comment]
Hi
@ssedai026, yes i have extracted data and its training very well. But my question is how i can generate custom dataset masks as used in mnist segmentation data. Kindly suggest any software or process for labelling objects coloured as done in mnist dataset and then generating corresponding masks.
Kindly help
Thanks

**Comment by ssedai026** [comment]
https://github.com/ilfrich/annotator

**Comment by ruchika61** [comment]
Thanks, i will work on that, thanks a lot
